# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en-au', 'English'), ('fr', 'French'), ('af', 'Afrikaans')], max_length=10, unique=True)),
                ('name_override', models.CharField(blank=True, help_text='Override the default name displayed for this language. Leave this field blank to use the default name.', max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Whether this language is available to visitors')),
            ],
        ),
    ]
